# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Web App Node.js CI

on:
  push:
    branches: [ master ]
    paths:
      - 'web-app/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'web-app/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      env: # Or as an environment variable
        super_secret: ${{ secrets.AWS_APP_ID }}
      with:
        node-version: ${{ matrix.node-version }} 
    - run: npm install -g @aws-amplify/cli
    - run: amplify configure --yes
    - run: amplify init --appId "$AWS_APP_ID" --envName "$AWS_BACKEND_ENV_NAME" --yes
    - run: npm ci
      working-directory: web-app
    - run: npm run build --if-present
      working-directory: web-app
    - run: npm test
      working-directory: web-app
